# -*- coding: utf-8 -*-
"""Bike sales analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FUtqedvMHoj8oJIN7kgN9SdNpVE91Qk
"""

from google.colab import drive
drive.mount("/content/Bike_sales_analysis")

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

df=pd.read_csv("/content/Bike_sales_analysis/MyDrive/Colab Notebooks/Sales.csv.zip")
(df)

df.head()

df.shape

df.info()

df.describe()

"""NUMERICAL ANALYSIS AND VISUALIZATION"""

df["Unit_Cost"].describe()

df["Unit_Cost"].mean()

df["Unit_Cost"].median()

df["Unit_Cost"].plot(kind="box",vert=False,figsize=(14,6))

df["Unit_Cost"].hist(bins=50, log=True, figsize=(12,6))

import matplotlib.pyplot as plt
df["Unit_Cost"].plot(kind="density", figsize=(14, 6))#kde
plt.title("Density Plot of Unit Cost")
plt.xlabel("Unit Cost")
plt.show()

ax=df["Unit_Cost"].plot(kind="density", figsize=(14, 6))#kde
ax.axvline(df["Unit_Cost"].mean(),color="red")
ax.axvline(df["Unit_Cost"].median(),color="green")

df.head()

df["Age_Group"].value_counts()

ax=df["Age_Group"].value_counts().plot(kind="pie",figsize=(6,6))
ax.set_ylabel("Number os Sales")

ax=df["Age_Group"].value_counts().plot(kind="bar",figsize=(6,6))
ax.set_ylabel("Number os Sales")

"""RELATIONSHIP BETWEEN COLUMNS"""

#correlations
#Use select_dtypes() to calculate correlation only on numeric columns
#  What Correlation Matrix Shows:
# It gives values between -1 and +1:

# +1 → strong positive relationship

# -1 → strong negative relationship

# 0 → no relationship

corr = df.select_dtypes(include='number').corr()
corr

"""🔍 Key Interpretation from Correlation Heatmap:

🔷 Strong Positive Correlations (values close to +1):

| Variables                | Correlation | Interpretation                                                                             |
| ------------------------ | ----------- | ------------------------------------------------------------------------------------------ |
| `Cost` ↔ `Revenue`       | **0.99**    | The more it costs you, the more revenue you make → you sell costlier items for more money. |
| `Profit` ↔ `Revenue`     | **0.96**    | More profit → more revenue. Strong indicator!                                              |
| `Unit_Cost` ↔ `Cost`     | **0.83**    | Unit cost strongly drives total cost (logical).                                            |
| `Unit_Price` ↔ `Revenue` | **0.82**    | Selling price contributes significantly to revenue.                                        |
| `Profit` ↔ `Unit_Price`  | **0.75**    | Higher price = higher profit.                                                              |
| `Profit` ↔ `Unit_Cost`   | **0.74**    | Higher unit cost may indicate premium products sold at high prices.    

🔶 Moderate to Weak Negative Correlations:                    

| Variables                       | Correlation     | Interpretation                                                                                             |
| ------------------------------- | --------------- | ---------------------------------------------------------------------------------------------------------- |
| `Order_Quantity` ↔ `Unit_Cost`  | **–0.52**       | When more units are ordered, the unit cost tends to be lower — possibly **bulk pricing** or cheaper items. |
| `Order_Quantity` ↔ `Unit_Price` | **–0.52**       | Customers order more units when items are cheaper.                                                         |
| `Order_Quantity` ↔ `Revenue`    | **–0.31**       | More quantity doesn’t always mean more revenue (if items are cheap).                                       |
| `Year` ↔ others                 | around **–0.2** | Slight trend over years — maybe product prices dropped slightly.                                           |

Near-Zero Correlations:

| Variable              | Reason why                                                                                 |
| --------------------- | ------------------------------------------------------------------------------------------ |
| `Day`, `Customer_Age` | Weak/no correlation with any financial metrics. May not be useful for predictive modeling. |

"""

import seaborn as sns  # Imports seaborn library for advanced statistical plotting

plt.figure(figsize=(10, 8))  # Creates a new figure with width=10 and height=8 inches

sns.heatmap(corr, annot=True, cmap="RdBu", center=0)
# Draws a heatmap using the correlation matrix `corr`
# `annot=True` displays the numeric correlation values in each cell
# `cmap="RdBu"` uses Red-Blue color scale (red = negative, blue = positive)
# `center=0` ensures 0 is the midpoint color (neutral correlation)

plt.title("Correlation Matrix")  # Adds a title to the heatmap

plt.show()  # Displays the plot

df.plot(kind="scatter",x="Customer_Age",y="Revenue",figsize=(6,6))

#or can use this formats down below
# import seaborn as sns

# plt.figure(figsize=(6, 6))
# sns.scatterplot(x="Customer_Age", y="Revenue", data=df)
# plt.title("Customer Age vs Revenue")
# plt.show()

# import matplotlib.pyplot as plt

# plt.figure(figsize=(6, 6))
# plt.scatter(df["Customer_Age"], df["Revenue"])
# plt.xlabel("Customer Age")
# plt.ylabel("Revenue")
# plt.title("Customer Age vs Revenue")
# plt.show()

df.plot(kind="scatter", x="Revenue",y="Profit",figsize=(6,6))

"""Interpretation:

🔹 Adults (35–64)
Have the widest range of profits.

Many outliers above 5000 and even over 15,000 → likely high-ticket purchases.

Higher median profit than other groups.

🔹 Seniors (64+), Young Adults (25–34), Youth (<25)
Tighter box → less spread.

Lower median profit.

Fewer extreme outliers than Adults group.

📊 Summary:

Adults (35–64) are your most profitable customers — they generate both high median and high extreme profits.

Youth and Young Adults tend to result in lower profits, possibly buying lower-priced or fewer items.

Seniors show similar patterns to youth — moderate profits, fewer high-value purchases.

🧠 Business Insight:

You may want to:

Target the Adults (35–64) with premium or upsell offers.

Explore marketing strategies to increase basket size or product type among younger groups.


"""

# Creates a boxplot of 'Profit' grouped by 'Age_Group'
# vert=True makes the boxes vertical
# figsize sets the width and height of the plot
ax = df[["Profit", "Age_Group"]].boxplot(by="Age_Group", vert=True, figsize=(10, 6))

# Sets the label for the y-axis to 'profit'
ax.set_ylabel("profit")

# List of numerical columns to visualize using boxplots
boxplot_cols = ["Year", "Customer_Age", "Order_Quantity", "Unit_Cost", "Unit_Price", "Profit"]

# Create boxplots for each column as subplots (2 rows, 3 columns layout)
df[boxplot_cols].plot(kind="box", subplots=True, layout=(2, 3), figsize=(10, 10))

"""COLUMN WRANGLING

We can create new columnas or modify existing ones
"""

df.dtypes

df["Revenue_per_Age"] = df["Revenue"] / df["Customer_Age"]
df["Revenue_per_Age"].head()

df["Revenue_per_Age"]=df["Revenue_per_Age"].astype(int)
df["Revenue_per_Age"].head()

df["Revenue_per_Age"].plot(kind="density",figsize=(14,6))

df["Revenue_per_Age"].plot(kind="hist",figsize=(14,6))

"""ADD AND CALCULATE A NEW CALCULATE_COST_COLUMN

calculated_cost=order_Quantity*unit_cost
"""

df["Calculated_Cost"]=df["Order_Quantity"]*df["Unit_Cost"]
df["Calculated_Cost"].head()

"""SELECTION & INDEXING(FILTERING)

Get all sales made in the of Kentucky
"""

# df.head()
# df.Country.unique()
# df.State.unique()
# df.State.value_counts()
df.loc[df.State=="Kentucky"]

"""How many records belong to age group youth(<25)or Adults(35-64)"""

df.loc[(df.Age_Group=="Youth (<25)") | (df.Age_Group=="Adults (35-64)").shape[0]]

"""Get mean revenue of the Adults(35-64) sales group"""

adults_avg_revenue = df.loc[df["Age_Group"] == "Adults (35-64)", "Revenue"].mean()
print(f"Average Revenue for Adults (35-64): {adults_avg_revenue}")

"""Get mean revenue of sales group adults(35-64) in United_States"""

# Explanation:
# Filters rows where both Age_Group is "Adults (35-64)" AND Country is "United States".

# Selects the "Revenue" column.

# Calculates the mean of those filtered values.

df.loc[(df["Age_Group"] == "Adults (35-64)") & (df["Country"] == "United States"),"Revenue"].mean()

"""increase the revenue by 10% to every sale made in France"""

df.loc[df["Country"] == "France", "Revenue"] *= 1.1

# df.head(60)
df.loc[df["Country"] == "France", "Revenue"].head()

df.loc[df["Country"] == "France", ["Country", "Revenue"]].head()